// <auto-generated />
using System;
using MealsEnPlace.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealsEnPlace.Api.Migrations
{
    [DbContext(typeof(MealsEnPlaceDbContext))]
    [Migration("20260420005436_DropTheMealDbIdColumn")]
    partial class DropTheMealDbIdColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.CanonicalIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DefaultUnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultUnitOfMeasureId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CanonicalIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Apples"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Asparagus"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000004"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Corn"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000005"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Kale"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000006"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Peaches"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000007"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Pumpkin"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000008"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Strawberries"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000009"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Tomatoes"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000010"),
                            Category = "Produce",
                            DefaultUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Name = "Zucchini"
                        });
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.ConsumeAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalIngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeductedQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("MealPlanSlotId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("OriginalExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("OriginalInventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalIngredientId");

                    b.HasIndex("MealPlanSlotId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("ConsumeAuditEntries");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalIngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalIngredientId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.MealPlanSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("ConsumedWithAutoDeplete")
                        .HasColumnType("boolean");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("MealPlanId", "DayOfWeek", "MealSlot")
                        .IsUnique();

                    b.ToTable("MealPlanSlots");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServingCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.RecipeDietaryTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Tag")
                        .IsUnique();

                    b.ToTable("RecipeDietaryTags");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalIngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsContainerResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalIngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.SeasonalityWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalIngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PeakSeasonEnd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeakSeasonStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsdaZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("7a");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalIngredientId");

                    b.ToTable("SeasonalityWindows");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000009"),
                            PeakSeasonEnd = "September",
                            PeakSeasonStart = "June",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000002"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            PeakSeasonEnd = "September",
                            PeakSeasonStart = "July",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000003"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000010"),
                            PeakSeasonEnd = "August",
                            PeakSeasonStart = "June",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000004"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000008"),
                            PeakSeasonEnd = "June",
                            PeakSeasonStart = "May",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000005"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            PeakSeasonEnd = "November",
                            PeakSeasonStart = "September",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000006"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            PeakSeasonEnd = "May",
                            PeakSeasonStart = "March",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000007"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000005"),
                            PeakSeasonEnd = "November",
                            PeakSeasonStart = "September",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000008"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            PeakSeasonEnd = "May",
                            PeakSeasonStart = "April",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000009"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000006"),
                            PeakSeasonEnd = "August",
                            PeakSeasonStart = "July",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000010"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000007"),
                            PeakSeasonEnd = "October",
                            PeakSeasonStart = "September",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000011"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            PeakSeasonEnd = "May",
                            PeakSeasonStart = "April",
                            UsdaZone = "7a"
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000012"),
                            CanonicalIngredientId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            PeakSeasonEnd = "October",
                            PeakSeasonStart = "September",
                            UsdaZone = "7a"
                        });
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalIngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalIngredientId");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("BaseUnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnitOfMeasureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("BaseUnitOfMeasureId");

                    b.ToTable("UnitsOfMeasure");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Abbreviation = "ea",
                            ConversionFactor = 1.0m,
                            Name = "Each",
                            UnitOfMeasureType = "Count"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Abbreviation = "g",
                            ConversionFactor = 1.0m,
                            Name = "Gram",
                            UnitOfMeasureType = "Weight"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Abbreviation = "ml",
                            ConversionFactor = 1.0m,
                            Name = "Milliliter",
                            UnitOfMeasureType = "Volume"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Abbreviation = "cup",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            ConversionFactor = 236.588m,
                            Name = "Cup",
                            UnitOfMeasureType = "Volume"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Abbreviation = "fl oz",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            ConversionFactor = 29.574m,
                            Name = "Fluid Ounce",
                            UnitOfMeasureType = "Volume"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Abbreviation = "L",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            ConversionFactor = 1000.0m,
                            Name = "Liter",
                            UnitOfMeasureType = "Volume"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Abbreviation = "pt",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            ConversionFactor = 473.176m,
                            Name = "Pint",
                            UnitOfMeasureType = "Volume"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Abbreviation = "qt",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            ConversionFactor = 946.353m,
                            Name = "Quart",
                            UnitOfMeasureType = "Volume"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Abbreviation = "tbsp",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            ConversionFactor = 14.787m,
                            Name = "Tablespoon",
                            UnitOfMeasureType = "Volume"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            Abbreviation = "tsp",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003"),
                            ConversionFactor = 4.929m,
                            Name = "Teaspoon",
                            UnitOfMeasureType = "Volume"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000011"),
                            Abbreviation = "kg",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            ConversionFactor = 1000.0m,
                            Name = "Kilogram",
                            UnitOfMeasureType = "Weight"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000012"),
                            Abbreviation = "lb",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            ConversionFactor = 453.592m,
                            Name = "Pound",
                            UnitOfMeasureType = "Weight"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000013"),
                            Abbreviation = "oz",
                            BaseUnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000002"),
                            ConversionFactor = 28.350m,
                            Name = "Ounce",
                            UnitOfMeasureType = "Weight"
                        });
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.UnitOfMeasureAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("UnitOfMeasureAliases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000001"),
                            Alias = "c",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000002"),
                            Alias = "c.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000003"),
                            Alias = "cups",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000010"),
                            Alias = "T",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000011"),
                            Alias = "T.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000012"),
                            Alias = "Tbs",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000013"),
                            Alias = "Tbs.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000014"),
                            Alias = "Tbl",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000015"),
                            Alias = "Tbsp.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000016"),
                            Alias = "tbsps",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000017"),
                            Alias = "tablespoons",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000020"),
                            Alias = "t",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000021"),
                            Alias = "t.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000022"),
                            Alias = "tsp.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000023"),
                            Alias = "tsps",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000024"),
                            Alias = "teaspoons",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000030"),
                            Alias = "oz.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000031"),
                            Alias = "ozs",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000032"),
                            Alias = "ozs.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000033"),
                            Alias = "ounces",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000040"),
                            Alias = "fl. oz",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000041"),
                            Alias = "fl. oz.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000042"),
                            Alias = "fluid oz",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000043"),
                            Alias = "fluid ounces",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000050"),
                            Alias = "lb.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000051"),
                            Alias = "lbs",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000052"),
                            Alias = "lbs.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000053"),
                            Alias = "pounds",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000060"),
                            Alias = "g.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000061"),
                            Alias = "gm",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000062"),
                            Alias = "gms",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000063"),
                            Alias = "grams",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000070"),
                            Alias = "kg.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000071"),
                            Alias = "kgs",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000072"),
                            Alias = "kilograms",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000080"),
                            Alias = "ml.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000081"),
                            Alias = "mls",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000082"),
                            Alias = "milliliters",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000090"),
                            Alias = "l",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000091"),
                            Alias = "l.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000092"),
                            Alias = "liters",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000093"),
                            Alias = "litres",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000100"),
                            Alias = "pt.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000101"),
                            Alias = "pts",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000102"),
                            Alias = "pints",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000110"),
                            Alias = "qt.",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000111"),
                            Alias = "qts",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000112"),
                            Alias = "quarts",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-0000-0000-000000000120"),
                            Alias = "each",
                            CreatedAt = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            UnitOfMeasureId = new Guid("a1000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.UnresolvedUnitOfMeasureToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SampleIngredientContext")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SampleMeasureString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UnitToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UnitToken");

                    b.ToTable("UnresolvedUnitOfMeasureTokens");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoDepleteOnConsume")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplaySystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Imperial");

                    b.HasKey("Id");

                    b.ToTable("UserPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_UserPreferences_SingleRow", "\"Id\" = 'd1000000-0000-0000-0000-000000000001'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            AutoDepleteOnConsume = false,
                            DisplaySystem = "Imperial"
                        });
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.WasteAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("MatchedRecipeIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("WasteAlerts");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.CanonicalIngredient", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", "DefaultUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("DefaultUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultUnitOfMeasure");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.ConsumeAuditEntry", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.CanonicalIngredient", "CanonicalIngredient")
                        .WithMany()
                        .HasForeignKey("CanonicalIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealsEnPlace.Api.Models.Entities.MealPlanSlot", "MealPlanSlot")
                        .WithMany("ConsumeAuditEntries")
                        .HasForeignKey("MealPlanSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalIngredient");

                    b.Navigation("MealPlanSlot");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.InventoryItem", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.CanonicalIngredient", "CanonicalIngredient")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CanonicalIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalIngredient");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.MealPlanSlot", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.MealPlan", "MealPlan")
                        .WithMany("Slots")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealsEnPlace.Api.Models.Entities.Recipe", "Recipe")
                        .WithMany("MealPlanSlots")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.RecipeDietaryTag", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.Recipe", "Recipe")
                        .WithMany("DietaryTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.CanonicalIngredient", "CanonicalIngredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("CanonicalIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealsEnPlace.Api.Models.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CanonicalIngredient");

                    b.Navigation("Recipe");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.SeasonalityWindow", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.CanonicalIngredient", "CanonicalIngredient")
                        .WithMany("SeasonalityWindows")
                        .HasForeignKey("CanonicalIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalIngredient");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.CanonicalIngredient", "CanonicalIngredient")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("CanonicalIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealsEnPlace.Api.Models.Entities.MealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalIngredient");

                    b.Navigation("MealPlan");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", "BaseUnitOfMeasure")
                        .WithMany("DerivedUnits")
                        .HasForeignKey("BaseUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnitOfMeasure");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.UnitOfMeasureAlias", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.WasteAlert", b =>
                {
                    b.HasOne("MealsEnPlace.Api.Models.Entities.InventoryItem", "InventoryItem")
                        .WithMany("WasteAlerts")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.CanonicalIngredient", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("SeasonalityWindows");

                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.InventoryItem", b =>
                {
                    b.Navigation("WasteAlerts");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.MealPlan", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.MealPlanSlot", b =>
                {
                    b.Navigation("ConsumeAuditEntries");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.Recipe", b =>
                {
                    b.Navigation("DietaryTags");

                    b.Navigation("MealPlanSlots");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MealsEnPlace.Api.Models.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("DerivedUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
